<script setup lang="ts">
import { computed } from 'vue'
import { Alert } from 'ant-design-vue'
import ReportHeader from './components/ReportHeader.vue'
import SummaryBar from './components/SummaryBar.vue'
import StepList from './components/StepList.vue'
import { loadReportData } from './data'

const report = loadReportData()

const failures = computed(() => report.steps.filter(s => s.status === 'failed'))
</script>

<template>
  <div class="app-container">
    <ReportHeader :report="report" />
    <SummaryBar :report="report" />

    <Alert
      v-if="report.error"
      type="error"
      :message="report.error"
      show-icon
      class="error-alert"
    />

    <StepList :steps="report.steps" />

    <div v-if="failures.length > 0" class="failures-section">
      <h2 class="failures-title">Failures</h2>
      <div v-for="f in failures" :key="f.step_id" class="failure-item">
        <b>{{ f.step_id }}</b>: {{ f.error || f.summary }}
      </div>
    </div>

    <div class="footer">Generated by Skiritai</div>
  </div>
</template>

<style>
/* Global reset */
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
  background: #f7f8fa;
  color: #333;
  padding: 32px 24px;
}
.app-container {
  max-width: 960px;
  margin: 0 auto;
}
.error-alert {
  margin-bottom: 16px;
}
.failures-section {
  background: #fff;
  border-radius: 8px;
  padding: 24px;
  border: 1px solid #ebeef5;
  margin-top: 8px;
}
.failures-title {
  color: #cf1322;
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 12px;
}
.failure-item {
  padding: 10px 0;
  border-bottom: 1px solid #f5f5f5;
  font-size: 13px;
  color: #595959;
}
.failure-item:last-child {
  border-bottom: none;
}
.footer {
  text-align: center;
  color: #d9d9d9;
  font-size: 12px;
  margin-top: 32px;
  letter-spacing: 0.3px;
}
</style>
