<script setup lang="ts">
import { computed } from 'vue'
import { Alert } from 'ant-design-vue'
import ReportHeader from './components/ReportHeader.vue'
import SummaryBar from './components/SummaryBar.vue'
import StepList from './components/StepList.vue'
import { loadReportData } from './data'

const report = loadReportData()

const failures = computed(() => report.steps.filter(s => s.status === 'failed'))
</script>

<template>
  <div class="app-container">
    <ReportHeader :report="report" />
    <SummaryBar :report="report" />

    <Alert
      v-if="report.error"
      type="error"
      :message="report.error"
      show-icon
      class="error-alert"
    />

    <StepList :steps="report.steps" />

    <div v-if="failures.length > 0" class="failures-section">
      <h2 class="failures-title">Failures</h2>
      <div v-for="f in failures" :key="f.step_id" class="failure-item">
        <b>{{ f.step_id }}</b>: {{ f.error || f.summary }}
      </div>
    </div>

    <div class="footer">Generated by Skiritai</div>
  </div>
</template>

<style>
/* Global reset */
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
  background: #f0f2f5;
  color: #333;
  padding: 24px;
}
.app-container {
  max-width: 960px;
  margin: 0 auto;
}
.error-alert {
  margin-bottom: 16px;
}
.failures-section {
  background: #fff;
  border-radius: 8px;
  padding: 24px;
  border: 1px solid #e8e8e8;
}
.failures-title {
  color: #c41e1e;
  font-size: 16px;
  margin-bottom: 12px;
}
.failure-item {
  padding: 8px 0;
  border-bottom: 1px solid #f0f0f0;
  font-size: 14px;
}
.failure-item:last-child {
  border-bottom: none;
}
.footer {
  text-align: center;
  color: #ccc;
  font-size: 12px;
  margin-top: 24px;
}
</style>
